import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.Basic
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.SourcePackage
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.SourceDependencies
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.Formalization
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.ReviewerBridge
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.TheoremStatement
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.MathlibObjects
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.AdmissibleClass
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.Projection
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.BridgeLemmas
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.GateLemmas
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.FinalTheorem
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.DualAlgebraBasics
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.WeakClosureProperties
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.SinglyGeneration
import DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean.FoundationStructure

namespace HautevilleHouse
namespace DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean

-- This module is the root of the DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean Lean proof package.

end DualAlgebrasWeaklyClosedSinglyFoundationCanonicalLaneLean
end HautevilleHouse
